src/Entity/Card.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\RangeFilter;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"},
 *     normalizationContext={"groups"={"card_listening:read"}},
 *     attributes={
 *          "pagination_client_enabled"=true,
 *          "pagination_items_per_page"=5,
 *          "pagination_fetch_join_collection"=true,
 *          "formats"={"jsonld", "json", "html", "jsonhal", "csv"={"text/csv"}}
 *     }
 * )
 * @ORM\Entity(repositoryClass="App\Repository\CardRepository")
 * @ApiFilter(OrderFilter::class, properties={"personalScore": "ASC", "countVictory": "ASC"})
 * @ApiFilter(RangeFilter::class, properties={"personalScore"})
 */
class Card
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"card_listening:read"})
     */
    private $id;

    /**
     * @ORM\Column(type="array")
     */
    private $status = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $checkSum;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="cards")
     * @Groups({"card_listening:read"})
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Store", inversedBy="cards")
     * @ORM\JoinColumn(name="store_id", referencedColumnName="id", onDelete="SET NULL")
     * @Groups({"card_listening:read"})
     */
    private $store;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Deal", inversedBy="cards")
     */
    private $deals;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Assert\Length(max="6", maxMessage="card.customer_code.maxlength")
     */
    private $customerCode;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CardActivity", mappedBy="card")
     * @Groups({"card_listening:read"})
     */
    private $activities;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\PositiveOrZero(message="card.fidelity_point.positiveozero")
     */
    private $fidelityPoint;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"card_listening:read"})
     * @Assert\PositiveOrZero(message="card.personal_score.positiveozero")
     */
    private $personalScore;

    /**
     * @var integer
     */
    private $countVictory;

    /**
     * @var integer
     */
    private $countGames;


    /**
     * Card constructor.
     */
    public function __construct()
    {
        $this->activities = new ArrayCollection();
        $this->deals = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return array|null
     */
    public function getStatus(): ?array
    {
        return $this->status;
    }

    /**
     * @param array $status
     * @return Card
     */
    public function setStatus(array $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCheckSum()
    {
        return $this->checkSum;
    }

    /**
     * @param mixed $checkSum
     * @return Card
     */
    public function setCheckSum($checkSum)
    {
        $this->checkSum = $checkSum;
        return $this;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return Card
     */
    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Store|null
     */
    public function getStore(): ?Store
    {
        return $this->store;
    }

    /**
     * @param Store|null $store
     * @return Card
     */
    public function setStore(?Store $store): self
    {
        $this->store = $store;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getActivities()
    {
        return $this->activities;
    }

    /**
     * @param CardActivity $activity
     * @return Card
     */
    public function addActivity(CardActivity $activity): self
    {
        if (!$this->activities->contains($activity)) {
            $this->activities[] = $activity;
            $activity->setCard($this);
        }

        return $this;
    }

    /**
     * @param CardActivity $activity
     * @return Card
     */
    public function removeActivity(CardActivity $activity): self
    {
        if($this->activities->contains($activity)){
            $this->activities->remove($activity);

            if($activity->getCard() === $this){
                $activity->setCard(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection|Deal[]
     */
    public function getDeals(): Collection
    {
        return $this->deals;
    }

    /**
     * @param Deal $deal
     * @return Card
     */
    public function addDeal(Deal $deal): self
    {
        if (!$this->deals->contains($deal)) {
            $this->deals[] = $deal;
        }

        return $this;
    }

    /**
     * @param Deal $deal
     * @return Card
     */
    public function removeDeal(Deal $deal): self
    {
        if ($this->deals->contains($deal)) {
            $this->deals->removeElement($deal);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCustomerCode()
    {
        return $this->customerCode;
    }

    /**
     * @param mixed $customerCode
     * @return Card
     */
    public function setCustomerCode($customerCode): self
    {
        $this->customerCode = $customerCode;
        return $this;
    }

    /**
     * @return string
     */
    public function getCode()
    {
        return $this->getStore()->getCenterCode() .
            $this->getCustomerCode() . $this->getCheckSum();

    }

    /**
     * @return string
     */
    public function getCardOwnerName()
    {
        return $this->getCode() . ' - ' . $this->getUser()->getFullName();
    }

    /**
     * @return int|null
     */
    public function getFidelityPoint(): ?int
    {
        return $this->fidelityPoint;
    }

    /**
     * @param int|null $fidelityPoint
     * @return Card
     */
    public function setFidelityPoint(?int $fidelityPoint): self
    {
        $this->fidelityPoint = $fidelityPoint;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getPersonalScore(): ?int
    {
        return $this->personalScore;
    }

    /**
     * @param int|null $personalScore
     * @return Card
     */
    public function setPersonalScore(?int $personalScore): self
    {
        $this->personalScore = $personalScore;

        return $this;
    }


    /**
     * @return int
     */
    public function getCountGamePlayed(){
        $game = 0;

        $games = $this->getActivities();

        foreach ($games as $g){
            $game += 1;
        }
        return $game;
    }


    /**
     * @return int
     */
    public function getCountWonGame(){
        $activities = $this->getActivities();
        $victories = 0;

        foreach ($activities as $activity){
            if($activity->getIsTheWinner() ==  true ){
                $victories += 1;
            }
        }
            return $victories;
        }

    /**
     * @return int
     * @Groups({"card_listening:read"})
     */
    public function getCountVictory(): int
    {
        return $this->getCountWonGame();
    }

    /**
     * @return int
     * @Groups({"card_listening:read"})
     */
    public function getCountGames(): int
    {
        return $this->getCountGamePlayed();
    }
    
}

src/Form/CardType.php
<?php

namespace App\Form;

use App\Entity\Card;
use App\Entity\Store;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class CardType
 * @package App\Form
 */
class CardType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'store',
            EntityType::class,
            [
                'class' => Store::class,
                'translation_domain' => 'forms',
                'label' => 'card.form.label.store_name',
                'choice_label' => 'name',
                'expanded' => false,
                'multiple' => false,
            ]
        );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Card::class,
        ]);
    }
}

templates/card/add_card.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rattacher une carte{% endblock %}

{% block body %}
    <div class="container container-admin ml-sm-auto col-md-7 col-lg-7 px-md-2 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Rattacher une carte</h1>
            {{ form_start(form)}}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form_row(form.card_number) }}
                </div>
            </div>
            <div class="text-right">
                <button type="submit" class="btn btn-primary">
                    Enregistrer
                </button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/card/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition carte  - {{ parent() }}{% endblock %}

{% block body %}
    {% include('admin/menu.html.twig') %}
    <div class="container container-admin ml-sm-auto col-md-7 col-lg-7 px-md-2 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Cartes de fidélités</h1>
        </div>
        {{ form_start(form) }}
        {{ form_row(form.store) }}
        <div class="text-right">
            <button type="submit" class="btn btn-primary">
                Enregistrer
            </button>
            <a href="{{ path('card_index') }}"
               class="btn btn-outline-secondary">
                Retour
            </a>
        </div>
        {{ form_end(form) }}
    </div>


{% endblock %}

templates/card/index.html.twig
{% extends 'base.html.twig' %}

    {% block title %}Cartes de fidélité - {{ parent() }}{% endblock %}

    {% block body %}
        {% include('admin/menu.html.twig') %}
        <div class="container container-admin ml-sm-auto col-md-7 col-lg-7 px-md-2 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Cartes de fidélités</h1>
            </div>

            <a href="{{ path('card_new') }}"
               class="btn btn-outline-primary mb-3">
                Créer une carte
            </a>
            <div class="table-responsive table-hover">
                <table class="table table-striped table-sm">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Numéro de carte</th>
                        <th scope="col">Centre</th>
                        <th scope="col">Statut</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for card in cards %}
                        <tr class="{% if card.id == last_card.0.id %} bg-secondary {% endif %}">
                            <th scope="row"
                                {% if card.id == last_card.0.id %}style="color:white" {% endif %}>{{ card.code }}</th>
                            <td {% if card.id == last_card.0.id %}style="color:white" {% endif %}>{{ card.store }}</td>
                            <td {% if card.id == last_card.0.id %}style="color:white" {% endif %}>
                                {% for key, value in card.status %}
                                    {{ key|trans({}, 'workflow') }}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="pagination justify-content-center">
                {{ knp_pagination_render(cards) }}
            </div>
        </div>


    {% endblock %}